<a href="https://colab.research.google.com/github/emanuel379/Calculo-Numerico/blob/main/C%C3%A1lculo_Num%C3%A9rico_M%C3%A9todo_da_pot%C3%AAncia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import linalg as lin
import math as m
import matplotlib.pyplot as plt

# Potência
def potencia(A,tol):
     k = 0; kmax = 10000; erro = np.inf
     n = np.shape(A)[0]; y0 = np.zeros(n); y0[0] = 1

     while(erro > tol and k < kmax):
          x = A.dot(y0) # Obtendo nosso x para as demais operações,
          y = x/np.linalg.norm(x) # Calculando a razão entre x e sua norma para obter um y
          erro = np.abs(np.abs(y0.dot(y))-1) # Erro de cálculo
          y0 = y; k = k+1

     lambda_ = y.dot(A.dot(y)) # Obtendo o maior autovalor
     return lambda_, y, k

#Potência Inversa
def potencia_inv(A,tol):
      k = 0; kmax = 10000; erro = np.inf
      n = np.shape(A)[0]; y0 = np.zeros(n); y0[0] = 1

      while(erro > tol and k < kmax):
           x = np.linalg.inv(A).dot(y0) # Obtendo nosso x para as demais operações
           y = x/np.linalg.norm(x) # Calculando a razão entre x e sua norma para obter um y
           erro = np.abs(np.abs(y0.dot(y))-1) # Erro de cálculo
           y0 = y; k = k+1 # Considerando y0 a primeira iteração de y e incrementando um na iteração a cada passo executado

      lambda_ = y.dot(A.dot(y)) # Obtendo o menor autovalor
      return lambda_, y, k

# Exemplo
A = np.array([[-4, 14, 0],
              [ -5, 13, 0],
              [ -1, 0,2]], dtype='double')

print(A)
(D_python,V_python) = np.linalg.eig(A) # usando uma função pronta para calcular todos os autovalores com a função eig
print('Cálculo do maior autovalor em módulo de A')
(lambda_,y,k) = potencia(A,0.000001)
print('Potência: %.4f  usando %d iterações' %(lambda_,k))
print('Python: %.4f\n' %(np.max(abs(D_python))))

print('Cálculo do menor autovalor em módulo de A')
(lambda_inv,y,k) = potencia_inv(A,0.000001)
print('Potência Inversa: %.4f  usando %d iterações' %(lambda_inv,k))
print('Python: %.4f\n' %(np.min(abs(D_python))))

[[-4. 14.  0.]
 [-5. 13.  0.]
 [-1.  0.  2.]]
Cálculo do maior autovalor em módulo de A
Potência: 6.0043  usando 10 iterações
Python: 6.0000

Cálculo do menor autovalor em módulo de A
Potência Inversa: 1.9982  usando 16 iterações
Python: 2.0000



In [ ]:
#Potência Inversa
# Código anterior porém com função pronta para calcular o x

def potencia_inv(A,tol):
      k = 0; kmax = 10000; erro = np.inf
      n = np.shape(A)[0]; y0 = np.zeros(n); y0[0] = 1

      while(erro > tol and k < kmax):
           x = np.linalg.solve(A,y0)
           y = x/np.linalg.norm(x) # Calculando a razão entre x e sua norma para obter um y
           erro = np.abs(np.abs(y0.dot(y))-1) # Erro de cálculo
           y0 = y; k = k+1 # Considerando y0 a primeira iteração de y e incrementando um na iteração a cada passo executado

      lambda_ = y.dot(A.dot(y)) # Obtendo o menor autovalor
      return lambda_, y, k

# Exemplo
A = np.array([[-4, 14, 0],
              [ -5, 13, 0],
              [ -1, 0,2]], dtype='double')

print('Cálculo do menor autovalor em módulo de A')
(lambda_inv,y,k) = potencia_inv(A,0.000001)
print('Potência Inversa: %.4f  usando %d iterações' %(lambda_inv,k))
print('Python: %.4f\n' %(np.min(abs(D_python))))

Cálculo do menor autovalor em módulo de A
Potência Inversa: 1.9982  usando 16 iterações
Python: 2.0000

