<a href="https://colab.research.google.com/github/emanuel379/Calculo-Numerico/blob/main/C%C3%A1lculo_Num%C3%A9rico_LU_Cholesky.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Resolução de Sistemas Triangulares

1) Calcular a solução de um sistema triangular(inferior e superior).

In [ ]:
# Matriz triangular inferior

def TriangularInf(A, b):
  n = len(b)
  x = [0]*n # Matriz nula com comprimento n
  x[0] = b[0]/A[0][0]

  for i in list(range(1, n, 1)):
    s = 0
    for j in list(range(0, i, 1)):
      s = s + A[i][j]*x[j]

    x[i] = (b[i] - s)/(A[i][i])

  return x

# Dados
import numpy as np
A = np.array([[3, 2, 4],[0,(1/3), (2/3)],[0, 0, 1]]) # Matriz trianguar superior

A = A.T # Transposta da matriz triangular superior(triangular inferior)
b = [1, (5/3), 0]
x = TriangularInf(A, b)
x

[0.3333333333333333, 3.0, -3.333333333333333]

In [ ]:
# Matriz triangular superior

def TriangularSup(A, b):
  n = len(b)
  x = [0]*n
  x[n-1] = b[n-1]/A[n-1][n-1]

  for i in list(range(n - 1, 0, -1)):
    s = 0
    for j in list(range(i+1, n+1, 1)):
      s = s + A[i-1][j-1]*x[j-1]

    x[i-1] = (b[i-1] - s)/(A[i-1][i-1])

  return x

# Dados
import numpy as np
A = np.array([[3, 2, 4],[0,(1/3), (2/3)],[0, 0, 1]])
b = [1, (5/3), 0]
x = TriangularSup(A, b)
x

[-3.0000000000000004, 5.000000000000001, 0.0]

# Decomposição LU

2) Calcular a fatoração LU de uma matriz A, como podemos usar as funções anteriores para resolver o sistema:

In [ ]:
# Resolução com biblioteca implementada

import sympy
A = sympy.Matrix([[1, 2,0], [1, 3,1],[-2, 0,1] ])
b = sympy.Matrix([3, 5,-1])
L, U, _ = A.LUdecomposition()
print(L)
print(U)
x = A.solve(b)
print(x)

Matrix([[1, 0, 0], [1, 1, 0], [-2, 4, 1]])
Matrix([[1, 2, 0], [0, 1, 1], [0, 0, -3]])
Matrix([[1], [1], [1]])


In [ ]:
# Sem bibloteca implementada 1
# Retirado da internet

def lu(A):

    import numpy as np

    # Return an error if matrix is not square
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    n = A.shape[0]

    L = np.zeros((n,n),dtype='float64')
    U = np.zeros((n,n),dtype='float64')
    U[:] = A
    np.fill_diagonal(L,1) # fill the diagonal of L with 1

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i]
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:]
            U[j,i] = 0
    return (L,U)

A = np.array([[1, 2, 0],[1,3, 1],[-2, 0, 1]])

lu(A)

(array([[ 1.,  0.,  0.],
        [ 1.,  1.,  0.],
        [-2.,  4.,  1.]]),
 array([[ 1.,  2.,  0.],
        [ 0.,  1.,  1.],
        [ 0.,  0., -3.]]))

In [ ]:
# Sem bibloteca implementada 2

# Decomposição LU

import numpy as np

def decompLU(A):
    n = np.shape(A)[0]
    L = np.eye(n)
    U = np.zeros((n,n))
    for k  in np.arange(n):
      for j in np.arange(k,n):
        U[k,j]=A[k,j]
        for s in np.arange(k):
          U[k,j] = U[k,j] - L[k,s]*U[s,j]
      for i in np.arange(k+1,n):
        L[i,k]=A[i,k]
        for s in np.arange(k):
          L[i,k] = L[i,k] - L[i,s]*U[s,k]
        L[i,k] = L[i,k]/U[k,k]
    return L, U

A = np.array([[1, 2, 0],[1,3, 1],[-2, 0, 1]])

decompLU(A)

(array([[ 1.,  0.,  0.],
        [ 1.,  1.,  0.],
        [-2.,  4.,  1.]]),
 array([[ 1.,  2.,  0.],
        [ 0.,  1.,  1.],
        [ 0.,  0., -3.]]))

In [ ]:
# Decomposição LU com menos for

def LU( A ): # Realizando a decomposição LU

    n = A.shape[ 0 ]
    U = A.copy()
    L = np.eye(n)
    for j in range( n - 1 ):
       for i in range( j + 1, n ):
          L[ i, j ] = U[ i, j ] / U[ j, j ]
          U[ i, j : n ] = U[ i, j : n ] - L[ i, j ] * U[ j, j : n ]
    return ( L, U )

A = np.array([[1, 2, 0],[1,3, 1],[-2, 0, 1]])
LU(A)


In [ ]:
# Descobrindo os valores de x

def LUsolve2(A,b):
  n = np.shape(A)[0]
  L,U = decompLU(A)
  y = TriangularInf(L,b)
  x = TriangularSup(U,y)
  return x

# y = U*x
LUsolve2(A, b)

[1.00000000000000, 1.00000000000000, 1.00000000000000]

In [ ]:
# Outra forma

def LUsolve2(A,b):
  n = np.shape(A)[0]
  L,U = decompLU(A)
  TriangularInf(L,b)
  TriangularSup(U,y)
  return x

y = U*x
LUsolve2(A, b)

Matrix([
[1],
[1],
[1]])

Exercício proposto, cálculo da inversa da matriz A



In [ ]:
def inverter_matrix(A, I):
    for i in range(len(A)):
        iScaler = 1.0 / A[i][i]
        for j in range(len(A)):
            A[i][j] *= iScaler
            I[i][j] *= iScaler
        for k in list(range(len(A)))[0:i] + list(range(len(A)))[i+1:]:
            crScaler = A[k][i]
            for j in range(len(A)):
                A[k][j] = A[k][j] - crScaler * A[i][j]
                I[k][j] = I[k][j] - crScaler * I[i][j]
    return I

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

n = len(A)
I = np.zeros([n, n]) # Criando uma matriz de zeros para a identidade
for i in range(0, n):
  I[i][i] += 1

inverter_matrix(A, I)

array([[ 0.16666667,  0.        ,  0.        ],
       [ 0.07246377, -0.15217391,  0.08695652],
       [-0.13043478,  0.17391304,  0.04347826]])

In [ ]:
import numpy as np
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
A = np.array([[3, 2, 4],[0,(1/3), (2/3)],[0, 0, 1]])
print(np.linalg.inv(A))

[[ 0.33333333 -2.          0.        ]
 [ 0.          3.         -2.        ]
 [ 0.          0.          1.        ]]


# Eliminação de Gauss

In [ ]:
#Eliminação de Gauss

import numpy as np

def ElimGauss(a,b):
  n = len(b)
  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k] != 0.0:
        lam = a[i,k]/a[k,k]
        a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
        b[i] = b[i] - lam*b[k]
  return a, b

def SolveSis(a,b):
  n = len(b)
  a, b = ElimGauss(a,b)
  x = TriangularSup(a,b)
  return x
  #for k in range(n-1,-1,-1):
  #   b[k] = (b[k] - a[k,k+1:n].dot(b[k+1:n]))/a[k,k]
  #return b

#Exemplo
A = np.array([[2, 1,2], [4, 3,3],[6, 5,-1]])
b = np.array([-1,0,6])
x = SolveSis(A,b)
print(x)

[0.0, 1.0, -1.0]
