<a href="https://colab.research.google.com/github/emanuel379/Calculo-Numerico/blob/main/C%C3%A1lculo_Num%C3%A9rico_M%C3%A9todo_de_Francis_e_decomposi%C3%A7%C3%A3o_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# QR clásiica

import numpy as np
import math as m

def clgsQR(A):
   (m,n) = np.shape(A)
   Q = np.zeros((m,n))
   R = np.zeros((n,n))

   for j in np.arange(n):
        V = A[:,j]
        for i in np.arange(j):
           R[i,j] = Q[:,i].dot(A[:,j])
           V = V - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(V)
        Q[:,j] = V/R[j,j]

   return Q,R

# QR modificada

def mgsQR(A):
    (m,n) = np.shape(A)
    V = np.copy(A)
    Q = np.zeros((m,n))
    R = np.zeros((n,n))

    for j in np.arange(n):
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(V[:,j])
            V[:,j] = V[:,j] - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(V[:,j])
        Q[:,j] = V[:,j]/R[j,j]

    return Q,R

# Exemplo

B = np.array([[1, 1, 1],
              [1, 0, 2],
              [1, 0, 1],
              [0, 1, 3]], dtype='double')

print(B)
(m,n) = np.shape(B)

print('Calculando decomposição QR clássica\n')
(Q_c,R_c) = clgsQR(B)
print(Q_c); print(R_c)

print('Calculando o erro da decomposição QR clássica')
B_calc = Q_c.dot(R_c)
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c)
I = np.eye(n)
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))



print('Calculando decomposição QR modificada\n')
(Q_c,R_c) = mgsQR(B)
print(Q_c); print(R_c)

print('Calculando o erro da decomposição QR modificada')
B_calc = Q_c.dot(R_c)
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c)
I = np.eye(n)
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

# Comparando com a do Python

(Q_python,R_python) = np.linalg.qr(B)
print(Q_python)
print(R_python)
#print(Q_python.dot(R_python))

print('Calculando o erro da decomposição QR Python')
B_calc = Q_python.dot(R_python)
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_python).dot(Q_python)
I = np.eye(n)
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

[[1. 1. 1.]
 [1. 0. 2.]
 [1. 0. 1.]
 [0. 1. 3.]]
Calculando decomposição QR clássica

[[ 0.57735027  0.51639778 -0.60246408]
 [ 0.57735027 -0.25819889  0.51639778]
 [ 0.57735027 -0.25819889  0.0860663 ]
 [ 0.          0.77459667  0.60246408]]
[[1.73205081 0.57735027 2.30940108]
 [0.         1.29099445 2.06559112]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR clássica
O erro da decomposição é: 2.22e-16

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 4.41e-16

Calculando decomposição QR modificada

[[ 0.57735027  0.51639778 -0.60246408]
 [ 0.57735027 -0.25819889  0.51639778]
 [ 0.57735027 -0.25819889  0.0860663 ]
 [ 0.          0.77459667  0.60246408]]
[[1.73205081 0.57735027 2.30940108]
 [0.         1.29099445 2.06559112]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR modificada
O erro da decomposição é: 2.22e-16

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 4.41e-16

[[-0.57735027  0.51639778  0.

In [ ]:
# Método de Francis

def francis(A, tol, flag):
  if flag == 'classico':
    print('QR', flag, '\n')
    qr = clgsQR
  if flag == 'modificada':
    print('QR', flag, '\n')
    qr = mgsQR
  if flag == 'python':
    print('QR', flag, '\n')
    qr = np.linalg.qr

  n = np.shape(A)[0]
  A_local = np.copy(A)
  V = np.eye(n)
  erro = np.inf

  while erro > tol:
    [ Q, R] = qr(A_local)
    A_local = R.dot(Q)
    V = V.dot(Q)

    erro = np.max(np.max(np.abs(np.tril(A_local, -1))))

  D = np.diag(A_local)

  return D, V

B = np.array([[2, 1, 1],
              [1, 3, 5],
              [1, 5, 14]], dtype='double')

C = np.transpose(B).dot(B)
print(C)
n_c = np.shape(C)[0]

print('Calculando autovalores com método de Francis\n')

tol = 0.00001; flag = 'python'
( D, V) = francis( C, tol, flag)

print(V)
print(D)

print('\nChecando a ortogonalidade de V')

I_c = np.transpose(V).dot(V)
I = np.eye(n_c)
norm_I_c = np.linalg.norm(I-I_c, 'fro')
print(f'O erro de ortogonalidade é: {norm_I_c}')

[[  6.  10.  21.]
 [ 10.  35.  86.]
 [ 21.  86. 222.]]
Calculando autovalores com método de Francis

QR python 

[[-0.09178996  0.88530776  0.45585609]
 [-0.36234084  0.39671105 -0.8434035 ]
 [-0.92751481 -0.24259125  0.28436907]]
[257.67479601   4.72665188   0.59855212]

Checando a ortogonalidade de V
O erro de ortogonalidade é: 1.9456630760490943e-15
