<a href="https://colab.research.google.com/github/emanuel379/Calculo-Numerico/blob/main/Lista_1_C%C3%A1lculo_Num%C3%A9rico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Métodos Diretos

1) Escreva um programa que calcule a decomposi¸c˜ao LU de uma matriz e em seguida calcule
o determinante da mesma. Verifique seu c´odigo comparando o resultado obtido usando fun¸c˜oes
fornecidas por bibliotecas Python para as seguintes matrizes:
a) A =

2 −3 −1
3 2 −5
2 4 −1


b) B =

2 0 −1 0
0 1 2 0
−1 2 0 1
0 0 1 −2


2) Com as decomposi¸c˜oes obtidas no exerc´ıcio anterior, escreva um c´odigo que resolva os seguintes
sistemas lineares:
a) Ax = b em que b =
3
−9
−5

b) BX = Z em que Z =

1 0
0 0
0 1
0 0


In [ ]:
# 1 - a

# Decomposição LU

import numpy as np
def lu(A):

    # Garantindo que a operação não continue caso a matriz não seja quadrada
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    # Se a matriz for quadrada, teremos

    n = A.shape[0] # Calculando o tamanho da matriz

    # Criando duas matrizes de zeros do tamanho de A
    L = np.zeros((n,n),dtype='float64')
    U = np.zeros((n,n),dtype='float64')
    U[:] = A # Inserindo A em U
    np.fill_diagonal(L,1) # Colocando 1 na diagonal principal de L

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i] # Inserindo os elementos abaixo da diagonal principal de L
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:] # Inserindo os elemento que irão compor a matriz U
            U[j,i] = 0 # Inserindo 0 abaixo da diagonal principal de U
    det = np.linalg.det(L@U) # Calculando o determinante de A na decomposição LU
    print('O determinante de A é', round(det))
    return (L,U)

A = np.array([[2, -3, -1],[3, 2, -5],[2, 4, -1]])

lu(A)

O determinante de A é 49


(array([[1.        , 0.        , 0.        ],
        [1.5       , 1.        , 0.        ],
        [1.        , 1.07692308, 1.        ]]),
 array([[ 2.        , -3.        , -1.        ],
        [ 0.        ,  6.5       , -3.5       ],
        [ 0.        ,  0.        ,  3.76923077]]))

In [ ]:
# 2 - a

def TriangularInf(A, b):
  n = len(b)
  x = [0]*n # Matriz nula com comprimento n
  x[0] = b[0]/A[0][0]

  for i in list(range(1, n, 1)):
    s = 0
    for j in list(range(0, i, 1)):
      s = s + A[i][j]*x[j]

    x[i] = (b[i] - s)/(A[i][i])

  return x

def TriangularSup(A, b):
  n = len(b)
  x = [0]*n
  x[n-1] = b[n-1]/A[n-1][n-1]

  for i in list(range(n - 1, 0, -1)):
    s = 0
    for j in list(range(i+1, n+1, 1)):
      s = s + A[i-1][j-1]*x[j-1]

    x[i-1] = (b[i-1] - s)/(A[i-1][i-1])

  return x

def LUsolve(A,b):
  n = np.shape(A)[0]
  L,U = lu(A)
  y = TriangularInf(L,b)
  x = TriangularSup(U,y)
  return x

A = np.array([[2, -3, -1],[3, 2, -5],[2, 4, -1]])
b = [3, -9, -5]
LUsolve(A, b)

O determinante de A é 49


[0.653061224489796, -1.1428571428571428, 1.7346938775510203]

In [ ]:
# Comparando com o determinante de A
det = np.linalg.det(A)
print('O determinante de A é', round(det))

O determinante de A é 49


In [ ]:
# Comparando com a biblioteca implementada

import sympy
A = sympy.Matrix([[ 2, -3, -1], [3, 2, -5],[2, 4,-1]])
b = sympy.Matrix([3, -9, -5])
L, U, _ = A.LUdecomposition()
print(L)
print(U)
x = A.solve(b)
print(x)

Matrix([[1, 0, 0], [3/2, 1, 0], [1, 14/13, 1]])
Matrix([[2, -3, -1], [0, 13/2, -7/2], [0, 0, 49/13]])
Matrix([[32/49], [-8/7], [85/49]])


In [ ]:
# 1 - b

# Decomposição LU

import numpy as np
def lu(A):

    # Garantindo que a operação não continue caso a matriz não seja quadrada
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    # Se a matriz for quadrada, teremos

    n = A.shape[0] # Calculando o tamanho da matriz

    # Criando duas matrizes de zeros do tamanho de A
    L = np.zeros((n,n),dtype='float64')
    U = np.zeros((n,n),dtype='float64')
    U[:] = A # Inserindo A em U
    np.fill_diagonal(L,1) # Colocando 1 na diagonal principal de L

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i] # Inserindo os elementos abaixo da diagonal principal de L
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:] # Inserindo os elemento que irão compor a matriz U
            U[j,i] = 0 # Inserindo 0 abaixo da diagonal principal de U
    det = np.linalg.det(L@U) # Calculando o determinante de A na decomposição LU
    print('O determinante de B é', round(det))
    return (L,U)

B = np.array([[2, 0, -1, 0],[0, 1, 2, 0],[-1, 2, 0, 1],[0, 0, 1, -2]])
lu(B)

O determinante de B é 16


(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ],
        [-0.5       ,  2.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        , -0.22222222,  1.        ]]),
 array([[ 2.        ,  0.        , -1.        ,  0.        ],
        [ 0.        ,  1.        ,  2.        ,  0.        ],
        [ 0.        ,  0.        , -4.5       ,  1.        ],
        [ 0.        ,  0.        ,  0.        , -1.77777778]]))

In [ ]:
# 2 - b

def TriangularInf(A, b):
  n = len(b)
  x = [0]*n # Matriz nula com comprimento n
  x[0] = b[0]/A[0][0]

  for i in list(range(1, n, 1)):
    s = 0
    for j in list(range(0, i, 1)):
      s = s + A[i][j]*x[j]

    x[i] = (b[i] - s)/(A[i][i])

  return x

def TriangularSup(A, b):
  n = len(b)
  x = [0]*n
  x[n-1] = b[n-1]/A[n-1][n-1]

  for i in list(range(n - 1, 0, -1)):
    s = 0
    for j in list(range(i+1, n+1, 1)):
      s = s + A[i-1][j-1]*x[j-1]

    x[i-1] = (b[i-1] - s)/(A[i-1][i-1])

  return x

def LUsolve(A,b):
  n = np.shape(A)[0]
  L,U = lu(B)
  y = TriangularInf(L,b)
  x = TriangularSup(U,y)
  return x

B = np.array([[2, 0, -1, 0],[0, 1, 2, 0],[-1, 2, 0, 1],[0, 0, 1, -2]])
b = np.array([[1, 0],[0, 0],[0, 1],[0, 0]])
LUsolve(B, b)

O determinante de B é 16


[array([ 0.4375, -0.125 ]),
 array([0.25, 0.5 ]),
 array([-0.125, -0.25 ]),
 array([-0.0625, -0.125 ])]

In [ ]:
# Comparando com o determinante de B
det = np.linalg.det(B)
print('O determinante de B é', round(det))

O determinante de B é 16


In [ ]:
# Comparando com a biblioteca implementada

import sympy
B = sympy.Matrix([[2, 0, -1, 0],[0, 1, 2, 0],[-1, 2, 0, 1],[0, 0, 1, -2]])
b = sympy.Matrix([[1, 0],[0, 0],[0, 1],[0, 0]])
L, U, _ = B.LUdecomposition()
print(L)
print(U)
x = B.solve(b)
print(x)

Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [-1/2, 2, 1, 0], [0, 0, -2/9, 1]])
Matrix([[2, 0, -1, 0], [0, 1, 2, 0], [0, 0, -9/2, 1], [0, 0, 0, -16/9]])
Matrix([[7/16, -1/8], [1/4, 1/2], [-1/8, -1/4], [-1/16, -1/8]])


3) Escreva um c´odigo para resolver o sistema dado usando pivoteamento parcial:

0 0 2 1 2
0 1 0 2 −1
1 2 0 −2 0
0 0 0 −1 1
0 1 −1 1 −1
x =

1
1
−4
−2
−1
.
Resolva o mesmo sistema com o c´odigo elaborado no exerc´ıcio 2 (sem pivoteamento parcial) e
compare os resultados

In [ ]:
def sub_regressiva(U,y):
  n = np.shape(y)[0]
  x = np.zeros(n)

  for i in np.arange(n-1,-1,-1):
    x[i] = (y[i]-U[i,i+1:n].dot(x[i+1:n]))/U[i,i]

  return x

def sub_progressiva(L,b):
  n = np.shape(b)[0]
  z = np.zeros(n)

  for i in np.arange(n):
    z[i] = (b[i]-L[i,0:i].dot(z[0:i]))/L[i,i]
  return z

# LU com pivô

def fatoraLUpivo(A):
  U = np.copy(A)
  n = np.shape(U)[0]
  L = np.eye(n)
  P = np.copy(L)

  for j in np.arange(n-1):
      p = np.argmax(np.abs(U[j:n,j]))
      P[[j,p],:] = P[[p,j],:]
      U[[j,p],j:n] = U[[p,j],j:n]
      L[[j,p],0:j] = L[[p,j],0:j]

      for i in np.arange(j+1,n):
        L[i,j] = U[i,j]/U[j,j]
        U[i,j+1:n] = U[i,j+1:n] - L[i,j]*U[j,j+1:n]
        U[i,j] = 0

  return L,U,P

A = np.array([[0, 0, 2, 1, 2],
            [0, 1, 0, 2, -1],
             [1, 2, 0, -2, 0],
             [0, 0, 0, -1, 1],
             [0, 1, -1, 1, -1]])

b = np.array([1, 1, -4, -2, -1])

fatoraLUpivo(A)

(L,U,P) = fatoraLUpivo(A)
bpivo = P.dot(b)
ypivo = sub_progressiva(L,bpivo)
x_pivo_lu = sub_regressiva(U,ypivo)
print(x_pivo_lu)

[nan nan nan nan nan]


<ipython-input-154-c72d1ae652bd>:33: RuntimeWarning: invalid value encountered in long_scalars
  L[i,j] = U[i,j]/U[j,j]
<ipython-input-154-c72d1ae652bd>:33: RuntimeWarning: divide by zero encountered in long_scalars
  L[i,j] = U[i,j]/U[j,j]
<ipython-input-154-c72d1ae652bd>:15: RuntimeWarning: divide by zero encountered in double_scalars
  z[i] = (b[i]-L[i,0:i].dot(z[0:i]))/L[i,i]


4) Usando o c´odigo j´a elaborado para decomposi¸c˜ao LU com pivoteamento, escreva outro c´odigo
para inverter uma matriz qualquer. Aplique seu c´odigo para calcular a inversa da matriz
A =
0.6 −0.4 1.0
−0.3 0.2 0.5
0.6 −1.0 0.5
 .

In [ ]:
# LU com pivô

def fatoraLUpivo(A):
  U = np.copy(A)
  n = np.shape(U)[0]
  L = np.eye(n)
  P = np.copy(L)

  for j in np.arange(n-1):
      p = np.argmax(np.abs(U[j:n,j]))
      P[[j,p],:] = P[[p,j],:]
      U[[j,p],j:n] = U[[p,j],j:n]
      L[[j,p],0:j] = L[[p,j],0:j]

      for i in np.arange(j+1,n):
        L[i,j] = U[i,j]/U[j,j]
        U[i,j+1:n] = U[i,j+1:n] - L[i,j]*U[j,j+1:n]
        U[i,j] = 0

  return L,U,P

A = np.array([[0.6, -0.4, 1],
              [-0.3, 0.2, 0.5],
              [0.6, -1, 0.5]], dtype = 'double')

fatoraLUpivo(A)

<ipython-input-155-f452ffc7cc84>:16: RuntimeWarning: divide by zero encountered in double_scalars
  L[i,j] = U[i,j]/U[j,j]


(array([[ 1. ,  0. ,  0. ],
        [-0.5,  1. ,  0. ],
        [ 1. , -inf,  1. ]]),
 array([[ 0.6, -0.4,  1. ],
        [ 0. ,  0. ,  1. ],
        [ 0. ,  0. ,  inf]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

# Métodos Iterativos

1) Escreva dois c´odigos: um que resolva um sistema linear qualquer utilizando o m´etodo de
Gauss-Jacobi e outro utilizando Gauss-Seidel. Escolha algum dos sistemas da se¸c˜ao anterior e
resolva-o utilizando os dois m´etodos, compare os resultados obtidos com o m´etodo direto.


In [ ]:
import numpy as np
import math as m

# Gauss-Jacobi

def gauss_jacobi(A,b,x0,tol,flag):
    n = np.shape(A)[0]
    D = np.diag(np.diag(A))
    aux_C = np.linalg.solve(D,A)
    C = np.eye(n) - aux_C
    g = np.linalg.solve(D,b)
    kmax = 10000
    k = 0

    error = np.zeros(kmax)
    if flag:
      statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax)
    else:
      statment = (k<kmax)

    while statment:
      error[k] = np.linalg.norm(b-A.dot(x0))
      k = k+1
      x0 = C.dot(x0)+g
      if flag:
        statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax)
      else:
        statment = (k<kmax)

    if (k == kmax and flag):
      print('\nErro: o método não converge.\n')

    x = x0;
    return x,k,error

In [ ]:
# Gauss-Seidel

def gauss_seidel(A, b, x0, tol, flag):
  L = np.tril(A)
  R = np.triu(A,1)
  C = -np.linalg.solve(L,R)
  g = np.linalg.solve(L,b)
  kmax = 10000
  k = 0

  error = np.zeros(kmax)
  if flag:
      statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax)
  else:
      statment = (k<kmax)

  while statment:
      error[k] = np.linalg.norm(b-A.dot(x0))
      k = k+1
      x0 = C.dot(x0)+g
      if flag:
        statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax)
      else:
        statment = (k<kmax)

  if (k == kmax and flag):
      print('\\nErro: o método não converge.\\n')

  x = x0;
  return x,k,error

In [ ]:
A = np.array([[2, -3, -1],[3, 2, -5],[2, 4, -1]])
print(A)
b = [3, -9, -5]
print(b)

# Função Python
print('\nSolução Python:\n')
x = np.linalg.solve(A,b)
print(x)

input()

# Métodos Iterativos
n = np.shape(A)[0]
x0 = np.zeros(n)
tol = 0.00000001
print('\nSolução Gauss-Jacobi:\n')
(x_jacobi,k_jacobi,erro_jacobi) = gauss_jacobi(A,b,x0,tol,1)
print(x_jacobi)
print('%d iterações usadas' %(k_jacobi))

input()

print('\nSolução Gauss-Siedel:\n')
(x_siedel,k_siedel,erro_siedel) = gauss_seidel(A,b,x0,tol,1)
print(x_siedel)
print('%d iterações usadas' %(k_siedel))

[[ 2 -3 -1]
 [ 3  2 -5]
 [ 2  4 -1]]
[3, -9, -5]

Solução Python:

[ 0.65306122 -1.14285714  1.73469388]


Solução Gauss-Jacobi:

[-1.02774715e+308 -1.38844297e+308             -inf]
614 iterações usadas


Solução Gauss-Siedel:

[-6.06847790e+307 -1.01353898e+308             -inf]
369 iterações usadas


In [ ]:
# Método direto

def lu(A):

    # Garantindo que a operação não continue caso a matriz não seja quadrada
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    # Se a matriz for quadrada, teremos

    n = A.shape[0] # Calculando o tamanho da matriz

    # Criando duas matrizes de zeros do tamanho de A
    L = np.zeros((n,n),dtype='float64')
    U = np.zeros((n,n),dtype='float64')
    U[:] = A # Inserindo A em U
    np.fill_diagonal(L,1) # Colocando 1 na diagonal principal de L

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i] # Inserindo os elementos abaixo da diagonal principal de L
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:] # Inserindo os elemento que irão compor a matriz U
            U[j,i] = 0 # Inserindo 0 abaixo da diagonal principal de U
    det = np.linalg.det(L@U) # Calculando o determinante de A na decomposição LU
    print('O determinante de A é', round(det))
    return (L,U)

def TriangularInf(A, b):
  n = len(b)
  x = [0]*n # Matriz nula com comprimento n
  x[0] = b[0]/A[0][0]

  for i in list(range(1, n, 1)):
    s = 0
    for j in list(range(0, i, 1)):
      s = s + A[i][j]*x[j]

    x[i] = (b[i] - s)/(A[i][i])

  return x

def TriangularSup(A, b):
  n = len(b)
  x = [0]*n
  x[n-1] = b[n-1]/A[n-1][n-1]

  for i in list(range(n - 1, 0, -1)):
    s = 0
    for j in list(range(i+1, n+1, 1)):
      s = s + A[i-1][j-1]*x[j-1]

    x[i-1] = (b[i-1] - s)/(A[i-1][i-1])

  return x

def LUsolve(A,b):
  n = np.shape(A)[0]
  L,U = lu(A)
  y = TriangularInf(L,b)
  x = TriangularSup(U,y)
  return x

A = np.array([[2, -3, -1],[3, 2, -5],[2, 4, -1]])
b = [3, -9, -5]
LUsolve(A, b)

O determinante de A é 49


[0.653061224489796, -1.1428571428571428, 1.7346938775510203]

2) Dada a matriz esparsa
A =
3 −2 1 0 0 0
−2 4 −2 1 0 0
1 −2 4 −2 1 0
0 1 −2 4 −2 1
0 0 1 −2 4 −2
0 0 0 1 −2 3
,
resolva o sistema Ax = b, em que b = [10, −8, 10, 10, −8, 10]T utilizando algum dos c´odigos elaborados
no exerc´ıcio anterior. Em seguida, resolva este mesmo sistema utilizando algum c´odigo com
decomposi¸c˜ao LU. Qual c´odigo foi mais r´apido? Compare os resultados obtidos.


In [ ]:

def gauss_jacobi(A,b,x0,tol,flag):
    n = np.shape(A)[0]
    D = np.diag(np.diag(A))
    aux_C = np.linalg.solve(D,A)
    C = np.eye(n) - aux_C
    g = np.linalg.solve(D,b)
    kmax = 10000
    k = 0

    error = np.zeros(kmax)
    if flag:
      statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax)
    else:
      statment = (k<kmax)

    while statment:
      error[k] = np.linalg.norm(b-A.dot(x0))
      k = k+1
      x0 = C.dot(x0)+g
      if flag:
        statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax)
      else:
        statment = (k<kmax)

    if (k == kmax and flag):
      print('\nErro: o método não converge.\n')

    x = x0;
    return x,k,error

In [ ]:

def lu(A):

    # Garantindo que a operação não continue caso a matriz não seja quadrada
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    # Se a matriz for quadrada, teremos

    n = A.shape[0] # Calculando o tamanho da matriz

    # Criando duas matrizes de zeros do tamanho de A
    L = np.zeros((n,n),dtype='float64')
    U = np.zeros((n,n),dtype='float64')
    U[:] = A # Inserindo A em U
    np.fill_diagonal(L,1) # Colocando 1 na diagonal principal de L

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i] # Inserindo os elementos abaixo da diagonal principal de L
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:] # Inserindo os elemento que irão compor a matriz U
            U[j,i] = 0 # Inserindo 0 abaixo da diagonal principal de U
    det = np.linalg.det(L@U) # Calculando o determinante de A na decomposição LU
    print('O determinante de A é', round(det))
    return (L,U)

def TriangularInf(A, b):
  n = len(b)
  x = [0]*n # Matriz nula com comprimento n
  x[0] = b[0]/A[0][0]

  for i in list(range(1, n, 1)):
    s = 0
    for j in list(range(0, i, 1)):
      s = s + A[i][j]*x[j]

    x[i] = (b[i] - s)/(A[i][i])

  return x

def TriangularSup(A, b):
  n = len(b)
  x = [0]*n
  x[n-1] = b[n-1]/A[n-1][n-1]

  for i in list(range(n - 1, 0, -1)):
    s = 0
    for j in list(range(i+1, n+1, 1)):
      s = s + A[i-1][j-1]*x[j-1]

    x[i-1] = (b[i-1] - s)/(A[i-1][i-1])

  return x

def LUsolve(A,b):
  n = np.shape(A)[0]
  L,U = lu(A)
  y = TriangularInf(L,b)
  x = TriangularSup(U,y)
  return x

In [ ]:
import time

A = np.array([[3, -2, 1, 0, 0, 0],
              [-2, 4, -2, 1, 0, 0],
              [1, -2, 4, -2, 1, 0],
              [0, 1, -2, 4, -2, 1],
              [0, 0, 1, -2, 4, -2],
              [0, 0, 0, 1, -2, 4]])
b = [10, -8, 10, 10, -8, 10]

start = time.time()
LUsolve(A, b)
end = time.time()
print('O método direto levou', end - start, 'segundos')

tol = 0.00000001
n = np.shape(A)[0]
x0 = np.zeros(n)
start = time.time()
gauss_jacobi(A,b,x0,tol,1)
end = time.time()
print('O método iterativo Gauss-Jacobi levou', end - start, 'segundos')

start = time.time()
gauss_seidel(A,b,x0,tol,1)
end = time.time()
print('O método iterativo Gauss-Seidel levou', end - start, 'segundos')


O determinante de A é 576
O método direto levou 0.0007605552673339844 segundos
O método iterativo Gauss-Jacobi levou 0.17104411125183105 segundos
O método iterativo Gauss-Seidel levou 0.006398200988769531 segundos


In [ ]:
# Método direto
import numpy as np

def lu(A):

    # Garantindo que a operação não continue caso a matriz não seja quadrada
    if not A.shape[0]==A.shape[1]:
        raise ValueError("Input matrix must be square")

    # Se a matriz for quadrada, teremos

    n = A.shape[0] # Calculando o tamanho da matriz

    # Criando duas matrizes de zeros do tamanho de A
    L = np.zeros((n,n),dtype='float64')
    U = np.zeros((n,n),dtype='float64')
    U[:] = A # Inserindo A em U
    np.fill_diagonal(L,1) # Colocando 1 na diagonal principal de L

    for i in range(n-1):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i] # Inserindo os elementos abaixo da diagonal principal de L
            U[j,i:] = U[j,i:]-L[j,i]*U[i,i:] # Inserindo os elemento que irão compor a matriz U
            U[j,i] = 0 # Inserindo 0 abaixo da diagonal principal de U
    det = np.linalg.det(L@U) # Calculando o determinante de A na decomposição LU
    print('O determinante de A é', round(det))
    return (L,U)

A = np.array([[-1, 2, -2, 1],[-2, 2, -3, 0],[-2, 0, -1, -3],[-2, 0, 0, -2]])
lu(A)

O determinante de A é 4


(array([[1., 0., 0., 0.],
        [2., 1., 0., 0.],
        [2., 2., 1., 0.],
        [2., 2., 2., 1.]]),
 array([[-1.,  2., -2.,  1.],
        [ 0., -2.,  1., -2.],
        [ 0.,  0.,  1., -1.],
        [ 0.,  0.,  0.,  2.]]))